### ISSUE TITLE
No attribute 'seeds'

### ISSUE THREAD

**Issue by Yaochangyu00** [pyrddlgym-project/pyRDDLGym-rl#5]
When I run this command, 
```
python -m pyRDDLGym_rl.examples.run_stable_baselines  ChromaticDice_ippc2018 1  ppo 200
```

I encounter such an erro

```

Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Traceback (most recent call last):
  File "/home/ps/miniconda3/envs/ycy/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ps/miniconda3/envs/ycy/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/ps/M/ycy/pyRDDLGym-rl-main/pyRDDLGym_rl/examples/run_stable_baselines.py", line 57, in <module>
    main(**kwargs)
  File "/media/ps/M/ycy/pyRDDLGym-rl-main/pyRDDLGym_rl/examples/run_stable_baselines.py", line 37, in main
    model.learn(total_timesteps=steps)
  File "/home/ps/miniconda3/envs/ycy/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py", line 315, in learn
  return super().learn(
  File "/home/ps/miniconda3/envs/ycy/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 264, in learn
    total_timesteps, callback = self._setup_learn(
  File "/home/ps/miniconda3/envs/ycy/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 423, in _setup_learn
    self._last_obs = self.env.reset()  # type: ignore[assignment]
  File "/home/ps/miniconda3/envs/ycy/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 77, in reset
    obs, self.reset_infos[env_idx] = self.envs[env_idx].reset(seed=self._seeds[env_idx], **maybe_options)
  File "/home/ps/miniconda3/envs/ycy/lib/python3.8/site-packages/stable_baselines3/common/monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/ps/miniconda3/envs/ycy/lib/python3.8/site-packages/pyRDDLGym/core/env.py", line 308, in reset
    seed = next(self.seeds)
AttributeError: 'SimplifiedActionRDDLEnv' object has no attribute 'seeds'

```

 Could you please help me identify where the problem lies? Thank you very much.

**Comment by mike-gimelfarb** [comment]
Hi,
Sorry for late reply... busy week.
Which version of pyRDDLGym are you using, from github directly or pypi? Based on the error, the seed handling was removed from pyRDDLGym quite recently, but I do not recall that we uploaded these changes yet to pypi, even though the rl wrapper assumes the latest version. 
Could you try installing pyRDDLGym directly from git and let us know if the problem persists?

conda install git
pip install git+https://github.com/pyrddlgym-project/pyRDDLGym 

We will push these changes to pypi soon.

**Comment by mike-gimelfarb** [comment]
Hi, just another follow-up. Please download pyrddlgym-rl again from github if you already have an older version installed.
I did a lot of debugging and just patched this package to work with the latest version of pyrddlgym, as some changes in pyrddlgym were not ported here. Of course, you will need the latest pyrddlgym from github still.

**Comment by Yaochangyu00** [comment]
Hi, I'm sorry for replying to you today.，and thank you very much for your reply. Following your steps, I updated pyRDDLgym and Pyddlgym-rl from github, and now I can run the examples normally!I think the problem that existed before was probably caused by my previous direct use of pyRDDLgym and pyRDDLgym installed on pypi , but some of your changes were not uploaded to pipy simultaneously.
